/** UN/ECE Recommendation 20 birim kodları — portal `birim` alanı. */
export const Unit = {
  DAY: 'DAY',
  MONTH: 'MON',
  YEAR: 'ANN',
  HOUR: 'HUR',
  MINUTE: 'D61',
  SECOND: 'D62',
  PIECE: 'C62',
  PACKAGE: 'PA',
  BOX: 'BX',
  MILLIGRAM: 'MGM',
  GRAM: 'GRM',
  KILOGRAM: 'KGM',
  LITRE: 'LTR',
  TONNE: 'TNE',
  MILLIMETRE: 'MMT',
  CENTIMETRE: 'CMT',
  METRE: 'MTR',
  KILOMETRE: 'KTM',
  MILLILITRE: 'MLT',
  SQUARE_CENTIMETRE: 'CMK',
  CUBIC_CENTIMETRE: 'CMQ',
  SQUARE_METRE: 'MTK',
  CUBIC_METRE: 'MTQ',
  KILOWATT_HOUR: 'KWH',
  CARAT: 'CT',
  PAIR: 'PR',
  SET: 'SET',
  DOZEN: 'DZN',
  THOUSAND_PIECES: 'T3',
} as const

export type UnitCode = (typeof Unit)[keyof typeof Unit]
